### ISSUE TITLE
mailing list is down?

### ISSUE THREAD

**Issue by reviewher** [file/file-tests#5]
http://www.darwinsys.com/file/

> Announcements of new releases are made on the "file" mailing list.

The link http://mx.gw.com/mailman/listinfo/file is down: http://downforeveryoneorjustme.com/mx.gw.com

> Please report bugs to the bug tracker or the mailing list (see above).

The bug tracker http://bugs.gw.com/ is down: http://downforeveryoneorjustme.com/bugs.gw.com/

Where is the appropriate place to discuss bugs?  The main github repo https://github.com/file/file has issues disabled

**Comment by chrishiestand** [comment]
It's still down (or maybe just down again). This is a pretty fundamental project. Anyone know what happened? Does the project need to be adopted?

**Comment by thomasjfox** [comment]
The server with the mailinglist crashed. The new mailinglist can be found here:
https://mailman.astron.com/mailman/listinfo/file

It is now run by the project maintainer AFAIK.
