### ISSUE TITLE
Replace pickle with json

### ISSUE THREAD

**Issue by christian-intra2net** [file/file-tests#8]
I suggest replacing saved file-test results in db with json.
Reasons
(1) pickles are inherently unsafe, can easily contain arbitrary code that is executed upon unpickling
(2) json is easier to read and diff, so we can see changes in file(1)-output
(3) Changes in code to do this are minimal

Regarding (2): we are using pickle protocol 0 which is "human readable" but that is an overstatement compared to json. Also, the order of fields in .pickle files is arbitrary, so diffs show lots of "changes" that are just swaps of fields. With json we can fix the order setting arg sort_keys=True .

Contra:
(-1) everybody who is maintaining a database of pickles has to manually switch to json

I would gladly invest the half hour for implementing this if you agree

**Comment by glensc** [comment]
I approve the switch. back to you ;)

**Comment by christian-intra2net** [comment]
Created pull-request #9

**Comment by glensc** [comment]
@christian-intra2net the linked PR is merged, this issue can be closed?
